name: Deploy Azure Web Server

on:
  push:
    branches:
      - main

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Build (if applicable)
        working-directory: ./backend
        run: |
          if [ -f package.json ]; then
            npm run build || echo "No build step defined"
          fi

      - name: Ensure proper files are ready for deployment
        run: ls -R ./backend 

      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: projekt-techniki-internetowe
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          package: ./backend
